### PR TITLE
fix(startup): save startup time, thanks @rem, closes #40

### LINKED ISSUE #40: Slightly faster boot time
If you move https://github.com/greenkeeperio/greenkeeper/blob/master/src/index.js#L16-L21 to the end of your index.js it's slightly faster. I noticed this on nodemon WRT time to get output on the cli.

### PR DESCRIPTION
**Pull request by janl**
Thanks @remy!

### CODE REVIEW

**Comment by boennemann** [comment]
> Whenever you initiate the update notifier and it's not within the interval threshold, it will asynchronously check with npm in the background for available updates, then persist the result. The next time the notifier is initiated the result will be loaded into the .update property. **This prevents any impact on your package startup performance**. The check process is done in a unref'ed child process. This means that if you call process.exit, the check will still be performed in its own process.

I think this is already taken care of/this change doesn't make any difference.

**Comment by janl** [comment]
I could measure ~70ms time improvement consistently on my MBP

**Comment by boennemann** [comment]
I just wanted to add, except for the time it takes to load the library itself into memory. But this also means the notifier is only ever called when the command doesn't fail, which isn't that cool, given that a lot of fails could result from the CLI being outdated.

**Comment by janl** [comment]
good point, ignore.

**Comment by boennemann** [comment]
Addendum II: The defaults operation could be quite expensive. We could probably speed this up by just picking name and version first, and then applying the defaults.

**Pull request closed without merging**
