### PR TITLE
show URL if fail to open

### PR DESCRIPTION
**Pull request by ginpei**
Hi. I saw the same problem as #69. I'd like to see the URL even if I don't know the option `--verbose`.

```
$ greenkeeper login
                        oooo
                        `888
             .ooooooooo  888  ooooo
            8888' `8888  888 .88P'
            8888   8888  8888888.       g r e e n k e e p e r . i o
            `888bod88P'  888 `888b.
             `Yooooooo. o888o o8888o
                  `Y88b
            d88P   d888
            `Y8888888P'


Login from this URL: https://api.greenkeeper.io/login?id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

### CODE REVIEW

**Comment by finnp** [comment]
Hi @ginpei! 

I think this is a pretty helpful idea. Thank you for your PR.

One thing: Instead of using `setInterval`, could you use the `callback` of opener and catch the error there? It's undocumented, but you can see it implemented here: https://github.com/domenic/opener/blob/master/opener.js#L7

**Comment by ginpei** [comment]
That's what I was looking for on the document! OK I changed it.

I guess you prefer `err` to `error`, btw. :)

**Comment by finnp** [comment]
Yeah that looks good! We should probably create a PR for the documentation of `opener` as well 😅

@boennemann @christophwitzko Could one of you review this? LGTM

**Comment by boennemann** [comment]
Thank you :+1:

**Pull request merged**
