### PR TITLE
chore: remove package-lock.json

### PR DESCRIPTION
**Pull request by Realtin**

### CODE REVIEW

**Comment by janl** [comment]
Yeah, what’s the reasoning here? :)

**Comment by Realtin** [comment]
the package-lock conflicts are annoying with greenkeeper PRs, so much more manual work

**Comment by janl** [comment]
Sounds like something we should automate ;D

**Comment by gr2m** [comment]
one upcoming reason to have a package-lock.json on CI is https://github.com/zkat/cipm which makes installes from package-lock.json a lot faster than `npm install`

**Pull request merged**
