### PR TITLE
feat(manual_webhooks): optionally removes need for admin scope

### LINKED ISSUE #46: Manual webhooks setup, removes admin scope
This is technically doable, but requires some extra implementation bits to keep it secure.
Worthwhile feature for sure.

### PR DESCRIPTION
**Pull request by boennemann**
Closes #46, requires https://github.com/greenkeeperio/website/pull/18.

### CODE REVIEW

**Comment by phillipj** [comment]
Updated to v2.13.0 and followed the instructions described in https://greenkeeper.io/manual-webhooks.html wo/luck.

image

[nodejs/nodejs.org](https://github.com/nodejs/nodejs.org) is obviously not a private repo, but the nodejs org doesn't provide access to 3rd party GitHub applications.

On thing that comes to mind when going through the manual-webhooks setup mentioned, is `greenkeeper signup --force --no-admin` seems odd when I already have linked greenkeeper with my GitHub account. Tried doing `login --force --no-admin` as well, but still didn't get to enable the nodejs.org repo.

@boennemann any thoughts on what I'm doing wrong here?

**Comment by boennemann** [comment]
Hey @phillipj,

sorry about this. First of all `signup` and `login` are just aliased. I'll update the website to avoid confusion.

Secondly it looks like we're having a problem downgrading your Greenkeeper scope (be aware that there is only one scope for all of your orgs, so if you want to downgrade the scope just for nodejs creating a bot account might be a better idea).

If you want to downgrade the scope for your account would you mind trying `gk access` and then revoking the Greenkeeper application completely? After that `greenkeeper login --force --no-admin` should work.

We're working on a fix to do that automatically in the meantime.

Best,
Stephan

**Comment by phillipj** [comment]
Thanks for answering quickly! I'll try those steps tomorrow morning.

**Comment by phillipj** [comment]
@boennemann sadly revoking and logging in again had no effect. Still the same error when trying to enable nodejs.org. Anything else I can do on my end which helps you debug this?

**Comment by lpinca** [comment]
@phillipj did you try with a new bot account?

**Comment by phillipj** [comment]
@lpinca nope. I'll try with the nodejs-github-bot account

**Comment by phillipj** [comment]
No luck using the nodejs-github-bot account either :( That account has never been used with greenkeeper before, so having to downgrade the account should not relevant.

@boennemann you know anyone who has "no admin" up-n-running?

**Comment by lpinca** [comment]
@phillipj can we try again?

**Comment by phillipj** [comment]
@lpinca sure 👍

This is what I see when trying to install the Greenkeeper integration:

screen shot 2017-05-06 at 16 41 48

Sadly the nodejs organization doesn't show, probably because I'm not an organization owner. Possibly something @Fishrock123 can give a shot?

**Pull request merged**
