### PR TITLE
Use https in package.json and update link in README.md

### PR DESCRIPTION
**Pull request by JuanitoFatas**
:gift:

### CODE REVIEW

**Comment by janl** [comment]
brilliant, thanks! :)

**Comment by JuanitoFatas** [comment]
:raising_hand: Wondering where in the code to update the reference in the commit message:

[screenshot 2016-04-15 02 25 00](https://github.com/netiam/demo/pull/85/commits/cf4c80e037513edf47320b5721d5806e3fea1269)

**Comment by boennemann** [comment]
@JuanitoFatas That's in the private part of the project. I'll update it right away. Thanks again :+1:

**Comment by JuanitoFatas** [comment]
> @JuanitoFatas That's in the private part of the project. I'll update it right away. Thanks again

I was also amazed so less code to achieve all these. This explains :smile:

**Pull request merged**
