### PR TITLE
feat(login): include private repositories for enterprise instances

### LINKED ISSUE #167: CLI prompt for private repositories
We have the GHE version of Greenkeeper and the site instructions on the instance don't mention needing to run `greenkeeper login --force --private` for private repositories. When getting people to enable it on their repos they always hit this issue. It would be great if its GHE to do a prompt or to add something in the site quick start about private repositories.

### PR DESCRIPTION
**Pull request by finnp**
This will run `--private` automatically on `gk login` for enterprise instances. This closes #167

### CODE REVIEW

**Comment by boennemann** [comment]
@finnp Thanks for this! I think we should add two things before we can merge:

1. Don't check for enterprise if the private flag is already true
2. Don't overwrite the private flag if it's set to false. There could be cases where enterprise customers wouldn't want to grant access to private repos. `--no-private` should still work for this.

**Comment by finnp** [comment]
Good points! I've updated the PR to treat the cases like this.

**Comment by boennemann** [comment]
Sorry for not coming up this in the first place, but could we also skip the enterprise check if the api value is the default value? That way common users would be entirely unaffected by this change. Maybe this could go into the `checkEnterprise` helper directly, would the also speed up the other cases.

After that merge at will :+1:

**Comment by boennemann** [comment]
Boom! Thanks :)

**Comment by boennemann** [comment]
@finnp Oh an can you add the `Closes #167` to the commit message body again, proper changelog etc. ;) (just use the squash merge feature)

**Pull request merged**
